### PR TITLE
fix(editor): Propagate normalization

### PR DESCRIPTION
**Pull request by BitPhinix**
Alternative to https://github.com/BitPhinix/slate-yjs/pull/282

### CODE REVIEW

**Comment by nemanja-tosic** [comment]
I can take a look tomorrow morning (I am in the CEST timezone fwiw).

Until then, what do you consider cleaner in this approach as compared to #282 so that I can understand your suggestion a bit better?

**Comment by BitPhinix** [comment]
It doesn't break the existing API (so no new major version needed for now) and doesn't mutate operations

**Comment by nemanja-tosic** [comment]
The changes work for the same tests i have, so i am ok with the changes functionality-wise.

I don't feel the changes in #282 break the existing API in a bad way - in #282 isRemote, asRemote, isLocal and asLocal were removed because i feel they are an implementation detail, and should be made private at least. Put another way - when would the client need to invoke said functions?

Bumping the major version is not something i thought was a big factor in decision making, but if it is i'll keep that in mind in the future.

In #284 we're adding localOperations and setLocalOperations, which in my mind should be private as when public they add to the same problem (breaking API changes, major bump) if we want to change the implementation later.

We're not mutating operations in #282, metadata is added to an operation generated by us. Metadata that is a Symbol and therefore non-enumerable and not really interesting to anyone but us. In theory, a factory function could add this metadata to all operations upon creation (having said factory function would be beneficial), but since there isn't such a function i added the metadata right before we apply operations, which was just the simplest point. However, it's important to say, no mutation is done, operations are enhanced with metadata and we can add the metadata on creation anyway.

Now, given that, the real question here becomes: to keep state or not to keep state. IOW, origin on YJS and metadata on slate ops vs statefull asRemote and asLocal.

Maintaining state usually implies cleaning it, dealing with memory etc, so the price of external state in this context is maintaining isRemote, asRemote, isLocal and asLocal. It means you need to be careful as to when you pick op the ops (change vs apply), do you do Promise.resolve().then(clean) or just clean, remember to try/catch/finally around fn() calls as to not keep the editor stuck in remote mode if an error is thrown, editor.localOperations might be overridden by another plugin, and everything else i might not have thought of. 

On the flip side, Yjs has a configurable origin for events, which they use in situations such as these (do not redo something i did in the first place), for example: https://github.com/yjs/y-websocket/blob/master/src/y-websocket.js#L259. Given Yjs supports said origin, we know if an event comes from us (as a response to a slate op) or is applied to the shared type by, say, a websocket connection. This transitively means that we know if a slate operation comes from an event too - we generate operations from events, and events have an origin property.

So now we know that a slate operation is remote or local, using the current lingo. The price to pay in this context is adding an origin to Yjs transactions (which is something Yjs does) and a property to slate operations. Adding a property to slate causes no TypeScript issues, so i would think they support that, even though their type definitions are a bit weird there.

I would personally always opt for stateless, as there is so much less to think about, and is much less error prone.

That being said, i am willing to work with this approach as well as i really need to fix this problem and remove the patches we have in place. If you feel this is the best way to go i have some suggestions to make as well, but i think this comment is long enough as is so i'll wait for you to read through it and tell me what you think we should do next :)

**Comment by BitPhinix** [comment]
> I don't feel the changes in #282 break the existing API in a bad way - in #282 isRemote, asRemote, isLocal and asLocal were removed because i feel they are an implementation detail, and should be made private at least. Put another way - when would the client need to invoke said functions?

I partly agree with you on that one. isLocal is useless to most external clients isRemote however isn't. There are a lot scenarios where plugins could act based on operations and whether they are caused by remote changes or user input. Like e.g. a history plugin.

> Bumping the major version is not something i thought was a big factor in decision making, but if it is i'll keep that in mind in the future.

It isn't that big of a factor but I'd like to avoid breaking the api whenever possible to keep the upgrade path as smooth as possible. I know of a few people that are using `isRemote` in custom plugins so that's definitely something we should keep.

> We're not mutating operations in #282, metadata is added to an operation generated by us. Metadata that is a Symbol and therefore non-enumerable and not really interesting to anyone but us. In theory, a factory function could add this metadata to all operations upon creation (having said factory function would be beneficial), but since there isn't such a function i added the metadata right before we apply operations, which was just the simplest point. However, it's important to say, no mutation is done, operations are enhanced with metadata and we can add the metadata on creation anyway.

For me, this feels too much like 'magic' and relies on no other plugin in the chain re-creating the operation. We are relying on metadata that isn't visible to the API consumer and that could be removed very easily by accident causing a debugging nightmare.

> Maintaining state usually implies cleaning it, dealing with memory etc, so the price of external state in this context is maintaining isRemote, asRemote, isLocal and asLocal. It means you need to be careful as to when you pick op the ops (change vs apply), do you do Promise.resolve().then(clean) or just clean, remember to try/catch/finally around fn() calls as to not keep the editor stuck in remote mode if an error is thrown, editor.localOperations might be overridden by another plugin, and everything else i might not have thought of.

IMO it isn't that big of a hassle and is also how the by slate provided plugins are currently implemented. Exception handling isn't part of the plugins concern and should result in most use-cases in the remounting of the editor anyway. If an exception occurs while applying remote or local operations/events we can't trust the yjs and editor state being in sync anyway. LocalOperations can't be overwritten by other plugins because the state is stored and consumed via the week map.

> On the flip side, Yjs has a configurable origin for events, which they use in situations such as these (do not redo something I did in the first place), for example: https://github.com/yjs/y-websocket/blob/master/src/y-websocket.js#L259. Given Yjs supports said origin, we know if an event comes from us (as a response to a slate op) or is applied to the shared type by, say, a websocket connection. This transitively means that we know if a slate operation comes from an event too - we generate operations from events, and events have an origin property.

I really like this way of figuring out whether a transaction/event was caused by us. That's something we should definitely keep/implement.

IMO the best way to go forward from here is to implement a hybrid approach of the 2 prs: Removing `isLocal` and replacing it using a yjs transaction origin and keeping the current isRemote/asRemote implementation. What do you think?

**Comment by nemanja-tosic** [comment]
> I partly agree with you on that one. isLocal is useless to most external clients isRemote however isn't. There are a lot scenarios where plugins could act based on operations and whether they are caused by remote changes or user input. Like e.g. a history plugin.

If  there are people already using it, it's ok. However, we are changing the contract for isRemote [here](https://github.com/BitPhinix/slate-yjs/pull/284/files#diff-1e4d81df527facc8432d4558ccb62693bf2156e5621cdda6e44710a1960c5089L63).

> For me, this feels too much like 'magic' and relies on no other plugin in the chain re-creating the operation. We are relying on metadata that isn't visible to the API consumer and that could be removed very easily by accident causing a debugging nightmare.

Fair enough, you're right.

> IMO it isn't that big of a hassle and is also how the by slate provided plugins are currently implemented. Exception handling isn't part of the plugins concern and should result in most use-cases in the remounting of the editor anyway. If an exception occurs while applying remote or local operations/events we can't trust the yjs and editor state being in sync anyway. LocalOperations can't be overwritten by other plugins because the state is stored and consumed via the week map.

[But it is on the editor too](https://github.com/BitPhinix/slate-yjs/pull/284/files#diff-1e4d81df527facc8432d4558ccb62693bf2156e5621cdda6e44710a1960c5089R46), i guess it doesn't have to be though.

Yeah, well, based on everything said the hybrid approach does appear to be the best way forward - use Yjs transaction origin and weak map for slate ops. I'd like to propose a couple of changes then to that end.

**Pull request closed without merging**
